Removed all of the try/except blocks
This really doesn't make the usage any better, since we are re-raising anyways.
Cleaned up the error message by not re-raising.

    OS_AUTH_URL not set, did you source openrc?
    Traceback (most recent call last):
      File "./gleek.py", line 207, in <module>
        main()
      File "./gleek.py", line 204, in main
        parse_args()
      File "./gleek.py", line 157, in parse_args
        default=os.environ['OS_AUTH_URL'])
      File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
        raise KeyError(key)
    KeyError: 'OS_AUTH_URL'